-- USERS


-- EVENTS
CREATE TABLE Events (
  id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  eventName VARCHAR(100),
  eventDate DATE,
  status VARCHAR(50)
);


-- VIDEOS
CREATE TABLE Videos (
    id CHAR(36) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    videoUrl VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP()
);

-- SEARCH PARAMETERS
CREATE TABLE SearchParameters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parameters VARCHAR(255) NOT NULL
);

-- POSTS
CREATE TABLE Posts (
    Id CHAR(36) PRIMARY KEY,
    Author VARCHAR(100) NOT NULL,
    Content TEXT NOT NULL,
    ImageUrl VARCHAR(255),
    VideoUrl VARCHAR(255),
    Likes INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- COMMENTS
CREATE TABLE Comments (
    CommentID INT AUTO_INCREMENT PRIMARY KEY,
    PostID CHAR(36),
    Author VARCHAR(100),
    Content TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PostID) REFERENCES Posts(Id)
);

-- LIKES
CREATE TABLE Likes (
    LikeID INT AUTO_INCREMENT PRIMARY KEY,
    PostID CHAR(36),
    LikedBy VARCHAR(100),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PostID) REFERENCES Posts(Id)
);

-- USER SETTINGS
CREATE TABLE UserSettings (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PasswordHash VARCHAR(256),
    ReceiveEmails BOOLEAN DEFAULT TRUE,
    ReceiveNotifications BOOLEAN DEFAULT TRUE,
    Theme VARCHAR(10) DEFAULT 'light',
    TwoFactorAuth BOOLEAN DEFAULT FALSE,
    AvatarUrl VARCHAR(256),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- QUIZZES
CREATE TABLE Quizzes (
    QuizID INT AUTO_INCREMENT PRIMARY KEY,
    Category VARCHAR(50),
    Title VARCHAR(100),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- QUESTIONS
CREATE TABLE Questions (
    QuestionID INT AUTO_INCREMENT PRIMARY KEY,
    QuizID INT,
    QuestionText TEXT,
    CorrectAnswer INT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (QuizID) REFERENCES Quizzes(QuizID)
);

-- OPTIONS
CREATE TABLE Options (
    OptionID INT AUTO_INCREMENT PRIMARY KEY,
    QuestionID INT,
    OptionText TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (QuestionID) REFERENCES Questions(QuestionID)
);

-- USER QUIZ RESULTS
CREATE TABLE UserQuizResults (
    ResultID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    QuizID INT,
    Score INT,
    TakenAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (QuizID) REFERENCES Quizzes(QuizID)
);

-- USER SCORES
CREATE TABLE UserScores (
rank1 int,
    UserID INT,
    QuizID INT,
    Score INT,
    PRIMARY KEY (UserID, QuizID),
    FOREIGN KEY (QuizID) REFERENCES Quizzes(QuizID)
);

-- PROFILES
CREATE TABLE Profiles (
    ProfileId CHAR(36) PRIMARY KEY,
    UserId INT,
    Username VARCHAR(100) NOT NULL,
    Role VARCHAR(50),
    AvatarUrl VARCHAR(255),
    Achievements TEXT,
    Skills TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(UserId)
);
